#!/bin/ash
#

shell() {
    /bin/busybox --install -s
    exec /bin/sh
}

rescue_shell() {
    echo "Something went wrong. Dropping you to a shell."
    shell
}

remote_rescue_shell() {
    # Bring up network interface
    ifconfig eth0 up
    udhcpc -t 5 -q -s /bin/simple.script

    # telnetd requires devpts
    mkdir -p /dev/pts
    mount -t devpts none /dev/pts

    # Start the telnet server
    telnetd

    # Continue with the local rescue shell
    rescue_shell
}

grep -q '\bshell\b' /proc/cmdline && rescue_shell

echo "Press any Key to drop to a shell"
countdown 3 "shell" ""
