#!/bin/ash
#
# This was canibalized from:
#   http://en.gentoo-wiki.com/wiki/Initramfs
#
# and modified by me.  I have not tested the
# remote_rescue_shell, as provided, so I would 
# not deploy it into a mission critical situation
# without thurougly testing it.
#
# Add ALLOWSHELL=N before including this to have it 
# prompt for N seconds to drop to a shell.
#

ALLOWSHELL="${ALLOWSHELL:-0}"

shell() {
    exec /bin/sh
}

rescue_shell() {
    echo "Something went wrong. Dropping you to a shell."
    shell
}

remote_rescue_shell() {
    # Bring up network interface
    ifconfig eth0 up
    udhcpc -t 5 -q -s /bin/simple.script

    # telnetd requires devpts
    mkdir -p /dev/pts
    mount -t devpts none /dev/pts

    # Start the telnet server
    telnetd

    # Continue with the local rescue shell
    rescue_shell
}

grep -q '\bshell\b' /proc/cmdline && shell

[ $ALLOWSHELL -ne 0 ] || return
echo "Press any Key to drop to a shell" 
countdown $ALLOWSHELL "shell" ""
